-- Active: 1782586374370@@127.0.0.1@5432@mohirjon_ai@public
CREATE TABLE conversations(
    id SERIAL PRIMARY KEY,
    peer_id BIGINT NOT NULL UNIQUE,
    peer_type VARCHAR(20) NOT NULL,
    title VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'WATCHING',
    mode VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);